name: CD - Crates Publish

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  publish_cargo:
    name: Publish in Crates.io
    runs-on: ubuntu-latest
    needs:
      - test
      
    steps:
    - uses: actions/checkout@v3
    - name: Login in Crates.io
      run: cargo login ${{ secrets.CARGO_TOKEN }}
    - name: Publish
      run: cargo publish --verbose
      
  publish_aur:
    name: Publish in AUR Package
    runs-on: ubuntu-latest
    needs:
      - test
      
    steps:
      - uses: actions/checkout@v3
      - name: Install and Run Cargo AUR to gen PKGBUILD
        run: cargo install cargo-aur && cargo aur && cat ./PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.6.0
        with:
          pkgname: treq-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
